name: PR Changed Files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  list-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          separator: ","

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: >-
            ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "Changed files:"
          IFS=',' read -ra CHANGED_FILES <<< "$ALL_CHANGED_FILES"
          for file in "${CHANGED_FILES[@]}"; do
            echo "  - $file"
          done
